name: Update Images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  github-readme-stats:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Stats
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&theme=nord&show_icons=true&hide_border=true&text_bold=false&hide_title=true
          path: images/stats.svg
          # token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add images/stats.svg
          git commit -m "Update Github Readme Stats" || exit 0
          git push

  wakatime-charts:
    name: Update wakatime stats charts
    runs-on: ubuntu-latest
    steps:
      - uses: Fr4nk1inCs/wakatime-charts@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          BRANCH_NAME: "main"
          COMMIT_MESSAGE: "Wakatime Github Action"
