name: Update Images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-images:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate Readme Stats
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&theme=nord&show_icons=true&text_bold=false&title_color=eceff4&ring_color=88c0d0
          path: images/stats.svg
          # token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit Readme Stats
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add images/stats.svg
          git commit -m "Update Github Readme Stats" || exit 0
          git push

      - name: Wakatime charts
        uses: Fr4nk1inCs/wakatime-charts@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          BRANCH_NAME: "main"
          COMMIT_MESSAGE: "Wakatime Github Action"
